name: Dimabot
version: 0.3

repo:
  owner: Feleuxens
  name: Dimabot
  icon: "https://github.com/Feleuxens.png"
  link: "https://github.com/Feleuxens/Dimabot/"

prefix:
  default: .
  server:
    0: "."